require 'plugins.packer'
require 'plugins.lsp-config'
require 'plugins.cmp'
require 'plugins.treesitter'
require 'plugins.tree'
require 'plugins.persistence'
require 'plugins.telescope'
require 'plugins.dap'
require 'plugins.vimsence'
require 'plugins.vista'
require 'plugins.vimux'
require 'plugins.snes'

require 'settings'
require 'keymaps'
