require 'plugins.packer'
require 'plugins.lsp-config'
require 'plugins.cmp'
require 'plugins.treesitter'
require 'plugins.tree'
require 'plugins.lualine'
require 'plugins.persistence'
require 'plugins.telescope'

require 'settings'
require 'keymaps'
