require 'plugins.paq'
require 'plugins.lsp-config'
require 'plugins.cmp'
require 'plugins.treesitter'
require 'plugins.tree'
require 'plugins.lualine'
require 'plugins.persistence'

require 'settings'
require 'keymaps'
